### ISSUE TITLE
Demo app force close when launching in iPhone

### ISSUE THREAD

**Issue by jorgefralves** [tuarua/AR-ANE#13]
Answer the below. **DO NOT DELETE!!**

- **What experience do you have with ARKit?**
    none

- **Have you read the README carefully?**
    yes
    
- **What version of the product are you using?**
    0.02

- **On what operating system?**
    OSX

- **Which IDE are you using?**
    IntelliJ

- **Which version of AIR are you using?**
    same results on 29 and 30 (beta)

- **What steps will reproduce the problem?**
    simple hello world project, just with the ane file, ios_dependencies folder, and the ARANE.swc

- **What is the expected output? What do you see instead?**
    build is sucessfully, but the ipa force closes when lauching in mobile device, 

- **Please provide any additional information below.**
    also tried to compile in animate CC with the same results, if I remove the ANE file it works just fine.

thanks in advance

**Comment by tuarua** [comment]
Did you run the example provided with the project Ok ?

To see the error that occurs, open Xcode > Window > Devices and Simulators > View Device Logs

If you are getting a crash on launch then it normally means the dependencies haven't been included correctly.
Unzip your .ipa. Open Payload > Right Click on Main > Package Contents. 
Confirm the frameworks have been packaged like so:

![image](https://user-images.githubusercontent.com/12083217/39971979-c6b8b5be-56fd-11e8-8afe-a2b959f8b0b6.png)

N.B. You don't need to include ARANE.swc. The ANE already contains the API.

**Comment by jorgefralves** [comment]
Hi, first of all thanks for the quick reply!

I was my fault, I was including the folder "device" inside the ios_dependencies and not the "Frameworks" folders.


Its working now.

And thanks for sharing this project, amazing work!
