### ISSUE TITLE
libARANE.a are required to have universal iOS librararies

### ISSUE THREAD

**Issue by yooni126** [tuarua/AR-ANE#14]
Answer the below. **DO NOT DELETE!!**

- **What experience do you have with ARKit?**
    - none

- **Have you read the README carefully?**
    - yes
    
- **What version of the product are you using?**
    - What version are you using?
0.2.0

- **On what operating system?**
    - OSX

- **Which IDE are you using?**
    - IntelliJ,

- **Which version of AIR are you using?**
    -30

- **What steps will reproduce the problem?**

- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**

When I comile my app I see this error ;

![1](https://user-images.githubusercontent.com/3766387/41206521-882425d0-6d1a-11e8-9b17-629e39930a81.JPG)

 I read your readme carefully and set framewors (like vibration ANE) and download ANE, assets and refrence_images as you can see in this pictures:

![2](https://user-images.githubusercontent.com/3766387/41206531-c315b3a2-6d1a-11e8-9f7e-9e4bd4e67b8b.JPG)
![3](https://user-images.githubusercontent.com/3766387/41206534-c61793f4-6d1a-11e8-9467-67a6e4950c96.JPG)

**Comment by tuarua** [comment]
Do you have **MinimumOSVersion** set to **11.0** ?
ArKit is iOS 11 & 64bit only

```xml
<InfoAdditions>
<![CDATA[
       <key>UIDeviceFamily</key>
       <array>
             <string>1</string>
            <string>2</string>
        </array>
       <key>MinimumOSVersion</key>
       <string>11.0</string>
      <key>NSCameraUsageDescription</key>
      <string>You need to allow camera to use ARKit</string>
]]>
</InfoAdditions>
```

**Comment by yooni126** [comment]
yes I set it in the manifest : 
<![CDATA[
       <key>UIDeviceFamily</key>
       <array>
             <string>1</string>
            <string>2</string>
        </array>
       <key>MinimumOSVersion</key>
       <string>11.0</string>
      <key>NSCameraUsageDescription</key>
      <string>You need to allow camera to use ARKit</string>
]]>

**Comment by tuarua** [comment]
Well, you are not referencing it instead using a generated one.

![image](https://user-images.githubusercontent.com/12083217/41249469-22df211a-6dac-11e8-9461-7fb4ab9999c5.png)

Please double check everything before raising issues.
I provided an IntelliJ project with the repo. Use it.

**Comment by yooni126** [comment]
ok! sorry for my mistake 
Now I check everything and  build is sucessfully, but the ipa force closes when lauching in mobile device,
I Unzip my.ipa. Open Payload > Right Click on Main > Package Contents.
and see the Framework folder is already in right place
![capture](https://user-images.githubusercontent.com/3766387/41257860-9349048e-6de3-11e8-86fa-3fc53154b0cb.JPG)
FYI I use  these addresses for Framework folder but nothing change:
![t1](https://user-images.githubusercontent.com/3766387/41258066-3b616a12-6de4-11e8-8fa7-f3646ca3e56b.JPG)
![t2](https://user-images.githubusercontent.com/3766387/41258071-3ed39030-6de4-11e8-8384-eddfad860d44.JPG)

**Comment by tuarua** [comment]
run this script to get ALL the dependencies
get_ios_dependencies.sh 
Closing.
