### ISSUE TITLE
Add AR-ANE to existing application which supports iOS version 7.0 and above

### ISSUE THREAD

**Issue by idzone** [tuarua/AR-ANE#16]
Answer the below. **DO NOT DELETE!!**

- **What experience do you have with ARKit?**
   - Some experience.

- **Have you read the README carefully?**
   - Yes
    
- **What version of the product are you using?**
    - What version are you using?
  - 0.3.0

- **On what operating system?**
    -OS X 10.13.5

- **Which IDE are you using?**
    -Flash Animate CC

- **Which version of AIR are you using?**
    -AIR 30.0.0107.

- **What steps will reproduce the problem?**
    - Try building application with minimumOSVersion 7.0. It gives me “MinimumOSVersion passed in app-xml is less than supported version, ignoring MinimumOSVersion value” error.

- **What is the expected output? What do you see instead?**
The application should run on every device with iOS version 7.0 and above with AR component disabled on device with iOS version below 11.0 and enabled on iOS version 11.0 and above. 

Currently it is not letting me publish app if i keep the minimum version below 11.0.

- **Please provide any additional information below.**
 I have an AIR application in iOS which currently runs on MinimumOSVersion 7.0. I want to add this AR ANE to my existing application. AR component will be visible only to devices with iOS 11.0 and above.
If I change the MinimumOSVersion to 7.0 in descriptor file it gives me following error while publishing “MinimumOSVersion passed in app-xml is less than supported version, ignoring MinimumOSVersion value”.
If I remove this two lines
 <key>MinimumOSVersion</key>
 <string>11.0</string>
it gives me “Error: libARANE.a are required to have universal iOS libraries. Please contact the ANE developer(s) to get the same.”
How do I add AR ANE so that it can run in my existing app supporting devices with iOS 7.0 and above.

**Comment by tuarua** [comment]
Not possible.
iOS 7 doesn't support dynamic frameworks which the ANE needs.
the MinimumOSVersion of the ANE is 11.0

**Comment by idzone** [comment]
Thanks for your response! I successfully published an ipa using example provided by you, but when I replace the “.dae” file inside assets folder, with my own “.dae” file created using blender it gives me “no cherub” as output. I have even named my file as “cherub.dae” and its placed inside same folder.
Does this ANE only supports specific type of .dae file? 
How do I add my own assets to it?

**Comment by tuarua** [comment]
The cherub dae was taken from this tutorial.
https://blog.pusher.com/building-an-ar-app-with-arkit-and-scenekit/

Pay attention to how you construct the model and the nodeName 
`Model(url:String, nodeName:String = null, flatten:Boolean = false)`

Note: The ANE is just a wrapper around ARkit. Knowing how to use ARkit is separate.
You should check the model is valid and you are able to import into Xcode yourself.
https://stackoverflow.com/questions/45404877/how-to-import-a-dae-to-scenekit-for-arkit

Closing as original ticket has been answered.
