### ISSUE TITLE
Convert local coordinate to world coordinate

### ISSUE THREAD

**Issue by testingOn** [tuarua/AR-ANE#20]
Answer the below. **DO NOT DELETE!!**

- **What experience do you have with ARKit?**
    - None

- **Have you read the README carefully?**
    -Yes
    
- **What version of the product are you using?**
    - What version are you using?
e.g. 0.5.0

- **On what operating system?**
    - OSX

- **Which IDE are you using?**
    -Flash Animate

- **Which version of AIR are you using?**
    - 29

- **What steps will reproduce the problem?**
    - I have to position the model based on local coordinate of the device.How do i do that?
Also how do I convert local coordinates to world coordinates?

- **What is the expected output? What do you see instead?**

- **Please provide any additional information below.**
    - A stack trace if available, any Exception information.Screengrabs.

**Comment by tuarua** [comment]
It is not clear what you are asking

**Comment by testingOn** [comment]
I want to drag model on my mobile device based on mouse position(onMouseMove). also i want to check if it collide with some other object on mouseUp

**Comment by tuarua** [comment]
Collision detection is in this example
https://github.com/tuarua/AR-ANE/blob/master/example/src/views/examples/PlaneDetectionExample.as

Gestures example
https://github.com/tuarua/AR-ANE/blob/master/example/src/views/examples/GestureExample.as

An ipad screen is 2D (X+Y) but a ARKit is 3D (X+Y+Z) so I don't know how you are expecting to convert those coordinates.

You shouldn't really open GitHub issues asking for code. It's up to you to build your app.The tracker is for bugs.
