### ISSUE TITLE
Simplified version of the ANE 

### ISSUE THREAD

**Issue by mspdevelopers** [tuarua/AR-ANE#7]
Answer the below. **DO NOT DELETE!!**

- **What experience do you have with ARKit?**
    - I tested it on Unity. Trying to make it work on Adobe AIR now.

- **Have you read the README carefully?**
    - Yes, This is not about the implementation.
    
- **What version of the product are you using?**
    - 0.0.6

- **On what operating system?**
    - Win10

- **Which IDE are you using?**
    - Flash Develop

- **Which version of AIR are you using?**
    - 28/29

- **What steps will reproduce the problem?**
    - No problem, just a feature request.

- **What is the expected output? What do you see instead?**
 -No problem, just a feature request

- **Please provide any additional information below.**
    - No problem, just a feature request.

I would like to know if you can create a version of the ANE that it's totally independent from the actual rendering. We are using Flare3D. I assume that the only thing that I need is the 3d camera matrix so I can replicate that with flare3d's camera and the matrices of the planes that the ANE detects.
 
 Do you think that it could be possible?

**Comment by tuarua** [comment]
No.
You cannot use the camera in AIR and access on native side (to perform the tracking) at the same time. 
Even if it was possible it would not be simple to make what you are asking for. It's not a feature but a whole new ANE and Open source != free labour.
